### ISSUE TITLE
Custom Theme Color preference in High Sierra.

### ISSUE THREAD

**Issue by djk4096** [pavanpodila/quicklens-uservoice#15]
It used to be a small box.
I first noticed this just after I updated the OS.

<img width="287" alt="high sierra prefs theme color issue" src="https://user-images.githubusercontent.com/1191147/31098804-ea5ce2ea-a791-11e7-84c5-334c6fa8665f.png">

**Comment by pavanpodila** [comment]
Thanks for reporting. Looks like an auto layout issue. Will put a fix out.

Thanks!


Pavan

**Comment by pavanpodila** [comment]
This won't be an issue anymore in the new Beta and beyond
