### ISSUE TITLE
QuickLens 2.0 Beta | Bring back the old logo

### ISSUE THREAD

**Issue by giri-jeedigunta** [pavanpodila/quicklens-uservoice#17]
@pavanpodila Loving the QuickLens 2.0 Beta... Even though the new app icon resonates with the trendy flat design ... I still love the previous logo ... would you consider bringing it back?

**Comment by pavanpodila** [comment]
Not the old logo but circular now. This is the new direction we are taking:

![app-icon-512](https://user-images.githubusercontent.com/156846/83728660-4ef76d00-a664-11ea-8697-23d4505b0bea.png)

**Comment by giri-jeedigunta** [comment]
This looks FANTASTIC !!!
