### ISSUE TITLE
Add a grab / rotation control to adjust the angle of ruler.

### ISSUE THREAD

**Issue by alffrey** [pavanpodila/quicklens-uservoice#22]
Having a grab / rotation control to adjust the angle of the ruler will be much more intuitive. Right now, the user has to guess and double click the orange pill section where the values are defined and then adjust the angle values there. This is an enhancement for sure.

**Comment by giri-jeedigunta** [comment]
You can precisely control the rotation with these Keyboard short-cuts  ... They are not yet published but all the cool / intuitive features are already available :) 

  "Command+KeypadMinus": "decreaseAngleBy1",
  "Command+-": "decreaseAngleBy1",
  "Command+KeypadPlus": "increaseAngleBy1",
  "Command+=": "increaseAngleBy1",
  "Command+Shift+KeypadMinus": "decreaseAngleBySnapAngle",
  "Command+Shift+-": "decreaseAngleBySnapAngle",
  "Command+Shift+KeypadPlus": "increaseAngleBySnapAngle",
  "Command+Shift+=": "increaseAngleBySnapAngle",
  "Space": "rotateCWToRightAngle",
  "Shift+Space": "rotateCCWToRightAngle",

**Comment by pavanpodila** [comment]
You can also hold Cmd key while you drag on the Ruler to rotate it :-)

**Comment by pavanpodila** [comment]
Closing this as its already part of the tool
