### ISSUE TITLE
2.0 - ruler, snap to major angles

### ISSUE THREAD

**Issue by luckman212** [pavanpodila/quicklens-uservoice#28]
Would be excellent if you could hold down SHIFT while adjusting the ruler angle to snap to 0 / 45 / 90 / 135 etc.

Adjunct:  ability to directly type in the angle would be nice too !

**Comment by pavanpodila** [comment]
Hi Luke, currently you can snap to 5° angles. I kept at 5°, since it gives the best balance between quick jumps and not having specific angle like 45°. Some folks also wanted 30°. Typing in the angle is a good idea. I'll add that to the list :-)

**Comment by luckman212** [comment]
@pavanpodila Oh I didn't realize snap was already implemented. I see it now! 🚀 

I have `Cmd + Shift [-/+]` bound to something else on my system. Is there any chance these hotkeys will be customizable in the final version?

**Comment by pavanpodila** [comment]
May not make it for the final version, but definitely in a subsequent update 👍

**Comment by pavanpodila** [comment]
We now have the ability to edit the angle directly in the settings
