### ISSUE TITLE
When resizing Frame, cursor only "activates" on the edge when moving from inside → outside

### ISSUE THREAD

**Issue by luckman212** [pavanpodila/quicklens-uservoice#29]
This one is a bit hard to explain, but maybe the screenshots will help.

When a Frame is onscreen, and you wish to resize it by dragging an edge, you have to first enter the frame with the mouse cursor and then slowly move outward towards the edge. If you instead approach the edge from _outside_ the frame, the resize cursor never appears and the drag is not possible. Is this by design, or a bug?

![image](https://user-images.githubusercontent.com/1992842/90634261-6c64bd80-e1f5-11ea-950a-f3c4d84d25bb.png)

![image](https://user-images.githubusercontent.com/1992842/90633924-eb0d2b00-e1f4-11ea-90b2-8620e8b1e7fe.png)

ver: **2.0.463**

**Comment by pavanpodila** [comment]
I think this is a bug in the macOS itself. I face the same problem sometime where the cursor is not changing correctly but the behavior of resizing does happen! Although it works for me most of the time.


![frame](https://user-images.githubusercontent.com/156846/91663331-c6268b00-eb05-11ea-8124-b8e9e5b3e1db.gif)

**Comment by luckman212** [comment]
Hmm. Interesting, are you on Catalina or Big Sur?

**Comment by pavanpodila** [comment]
catalina

**Comment by luckman212** [comment]
Me too. Well, maybe Big Sur will fix the OS bug then (doubt it!)

**Comment by pavanpodila** [comment]
Closing it for now as it doesn't seem to be a QuickLens issue
