### ISSUE TITLE
First impressions/Suggestions

### ISSUE THREAD

**Issue by nareshbhatia** [pavanpodila/quicklens-uservoice#34]
This is a blanket issue of first impressions and suggestions.

First off, thank you for this wonderful tool. It has become my "go-to" tool when developing front-ends.

Here are some observations/questions/suggestions:

## Welcome tour and shortcut viewer are fighting for attention

- I am not sure where to go when I need help on a function. Welcome tour has help imbedded in it, but it is not easily navigable. Shortcut viewer is also helpful, but it is very terse. What is really needed is a single in-app help that is easily accessible and navigable. Welcome tour can remain, but its function would be to give a tour of the functions and not how to use them.

- Welcome tour and shortcut viewer are under different menu items. I always look for the Shortcut viewer under the Help menu, but it is under the Window menu.

- Welcome tour should have ability to jump to any topic by clicking the appropriate icon on the main page.

-  The videos on the web site are too short to understand the behavior. They need a narrative. I really love how the [Concepts app](https://concepts.app/en/support) does it, with short videos by topic.

## Lens
- When using lens, I can never remember how to lock a color and copy it to the clipboard. This is the most important operation and should be very obvious in help and/or shortcut viewer. In shortcut viewer, the shortcuts are arranged as follows. Note that "Copying to Pasteboard" is buried at #4, although I think it is the most important function.

  - Color Management
  - Display Behavior
  - Copying to Pasteboard
  - Pixel Movement
  - ....

- The term "pasteboard" is confusing. Most users are familiar with the term "clipboard". Later I realized that pasteboard is the panel on the left of the Lens.

- "Add Color" shortcut (C) is sitting under Color Management, I couldn't have imagined that it would add a color to the pasteboard.

- "Command C" is for "Copy color to Pasteboard" but AFAIK it copies to the clipboard. This is confusing.

- It is not clear what I can use the pasteboard for. All I know is that it shows color values on hover. Perhaps it would be useful to copy the color value to the clipboard on a click.

- The cursor for the Lens tool is an arrow. It would be more precise to have a cross-hair instead.

## App icon
The app icon is nice, but the 3 things jutting out of the circle are very distracting. It is good detail, but the icon is too jarring with everything else on the dock, most items being clean circles or rectangles.

## Ruler
Ruler should lock at 0, 90, 180 & 270 degrees. It is too difficult to lock precisely at these angles when rotating.

## Crosshair
- Shortcut for "Cycle between modes" is not very legible. I have to squint to see that it is a back-tick.
- The various modes should be listed in the help.
- For quite a while, I was not able to figure out how to change the mode. Finally found out that the focus has to be on the crosshair in the tool palette to change the mode.

**Comment by pavanpodila** [comment]
Firstly thanks for such detailed feedback! Please see my comments below.


> ## Welcome tour and shortcut viewer are fighting for attention
> * I am not sure where to go when I need help on a function. Welcome tour has help imbedded in it, but it is not easily navigable. Shortcut viewer is also helpful, but it is very terse. What is really needed is a single in-app help that is easily accessible and navigable.

Full set of documentation is coming soon and will be hosted on quicklens.app so it can be updated quickly. Also a link to this will be added to the Help menu. This is in the works and will be ready for the **2.2** release.

> * Welcome tour and shortcut viewer are under different menu items. I always look for the Shortcut viewer under the Help menu, but it is under the Window menu.

Apparently, this is the way Mac Apps are organizing some content. XCode is an example. However your suggesting has merit and I'll think about making this change.

> * Welcome tour should have ability to jump to any topic by clicking the appropriate icon on the main page.

This is a neat suggestion. I've made that change and it will be part of **2.2**.

> * The videos on the web site are too short to understand the behavior. They need a narrative. I really love how the [Concepts app](https://concepts.app/en/support) does it, with short videos by topic.

I'll be recording a series of videos and will be part of the Online Documentation. They will have a narrative. Thanks for the link to Concepts. They do a great job and I'll take some inspiration from there :-).

> ## Lens
> * When using lens, I can never remember how to lock a color and copy it to the clipboard. This is the most important operation and should be very obvious in help and/or shortcut viewer. In shortcut viewer, the shortcuts are arranged as follows. Note that "Copying to Pasteboard" is buried at #4, although I think it is the most important function.
>   
>   * Color Management
>   * Display Behavior
>   * Copying to Pasteboard
>   * Pixel Movement
>   * ....
> * The term "pasteboard" is confusing. Most users are familiar with the term "clipboard". Later I realized that pasteboard is the panel on the left of the Lens.
> * "Add Color" shortcut (C) is sitting under Color Management, I couldn't have imagined that it would add a color to the pasteboard.
> * "Command C" is for "Copy color to Pasteboard" but AFAIK it copies to the clipboard. This is confusing.

You can lock the mouse using the `L` key and then `Command` `C` to copy to the clipboard (aka Pasteboard). Pasteboard is the term used on the Mac to refer to the Clipboard. I'll keep both terms in the docs too. I'll change the ordering of the categories in the Shortcuts viewer.


> * The cursor for the Lens tool is an arrow. It would be more precise to have a cross-hair instead.

Cursors can only be changed when the mouse if on the Lens Window. However most of time you will be outside the Lens, hence I chose to go with the Arrow cursor instead. The cross-hair cursor is used during Auto Palette.

> 
> ## App icon
> The app icon is nice, but the 3 things jutting out of the circle are very distracting. It is good detail, but the icon is too jarring with everything else on the dock, most items being clean circles or rectangles.

Will look into making this simpler.

> 
> ## Ruler
> Ruler should lock at 0, 90, 180 & 270 degrees. It is too difficult to lock precisely at these angles when rotating.

This already works today. Hit the `Space` key to snap to 90° angles in CW fashion and `Shift` `Space` to snap to 90° in CCW direction. You can see this in the Shortcuts Viewer for Ruler. Also if you hold the `Shift` key while rotating the ruler, it snaps to 5° angles.

> 
> ## Crosshair
> * Shortcut for "Cycle between modes" is not very legible. I have to squint to see that it is a back-tick.
> * The various modes should be listed in the help.
> * For quite a while, I was not able to figure out how to change the mode. Finally found out that the focus has to be on the crosshair in the tool palette to change the mode.

This will be added to the Online Documentation along with a video to make it easier to use.

**Comment by nareshbhatia** [comment]
Thank you for the quick response and clarifications, Pavan. I am now eagerly awaiting version 2.2.

**Comment by pavanpodila** [comment]
Closing this for now. Will create separate issues for the pending items
