### ISSUE TITLE
Tape angle measurement errors

### ISSUE THREAD

**Issue by cssjunkie** [pavanpodila/quicklens-uservoice#6]
I was playing around with the ellipse mode on the Tape tool, and found that when the main leg is moved off a orthogonal direction, the other leg can still snap to 90 degrees via the shift key, but the reported angle is other than 90 degrees.

Also the Tape tool very often will turn on extra Terminal windows for no reason when starting or stopping, but it doesn't happen every time. Only the Tape tool does this, and the Terminal does not need to be started for new windows to appear.

**Comment by pavanpodila** [comment]
Tape is no longer in the Suite of tools. We will probably create a new tool or make some of these features as part of Ruler
