### ISSUE TITLE
Global shortcut to remove any active tools from screen

### ISSUE THREAD

**Issue by dimitrieh** [pavanpodila/quicklens-uservoice#8]

**Comment by dimitrieh** [comment]
escape should also work for this i think ;)

**Comment by dimitrieh** [comment]
also be consistent in having a close button on each tool, as you offer them on certain tools like the guides:
- guide control palette has no close button
- ruler has no close button
- etc

**Comment by pavanpodila** [comment]
This has been addressed where every tool can be closed with the `ESC` key or using `Command+W`. Also all tools are now consistent and don't show a close option ;-)
